### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by o9zs** [ShashTheEpic/RCO-Auto-Installer#1]
On line 10 `RCO.text` returns the whole page in HTML, instead of the `ClientAppSettings.json` file, which leads to an error:
```
Traceback (most recent call last):
  File "c:\Users\\Documents\Programming\Python\RCO-auto-installer.py", line 24, in <module>ecting value", s, err.value) from N    json.dump(json.loads(RCO_text), f, indent=0)
              ^^^^^^^^^^^^^^^^^^^^cting value: line 1 column 1 (c  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loadsata/Local/Programs/Python/P    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
how fix?? ??"?"?

**Comment by ShashTheEpic** [comment]
@o9zs I'm not sure what happened. I am relatively new to Python and when I ran it it worked perfectly fine. Try running the following and tell me what happens. If it fails to write the ClientAppSettings.json, try replacing RCO_url with this: https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/assets/ClientAppSettings.json
```PY
import requests
import json
import os
import glob

RCO_url = "https://roblox-client-optimizer.simulhost.com/ClientAppSettings.json"
RCO = requests.get(RCO_url)

try:
    RCO.raise_for_status()  # Check if the request was successful
    RCO_text = RCO.text
    try:
        json_data = json.loads(RCO_text)
              # Finds the directory to RCO
        user = os.getlogin()
        RobloxVersionDir = rf"C:\Users\{user}\AppData\Local\Roblox\Versions"
        LatestRobloxVersionDir = max(glob.glob(os.path.join(RobloxVersionDir, "version-*")), key=os.path.getmtime)
        RobloxClientSettingsDir = os.path.join(LatestRobloxVersionDir, "ClientSettings", "ClientAppSettings.json")

        # If RCO isn't installed, it will be installed
        if not os.path.exists(os.path.dirname(RobloxClientSettingsDir)):
            os.makedirs(os.path.dirname(RobloxClientSettingsDir))

        # Latest version of RCO writes/overwrites current ClientAppSettings.json
        with open(RobloxClientSettingsDir, "w") as f:
            json.dump(json_data, f, indent=0)

        # Informs user that RCO has been updated/installed and the directory
        print("New data has been written to", RobloxClientSettingsDir)
    except json.JSONDecodeError as e:
        print("Error occurred while parsing the JSON:", e)
except requests.exceptions.RequestException as e:
    print("Error occurred while fetching the JSON file:", e)

```

**Comment by ShashTheEpic** [comment]
Alternatively, if everything we try doesn't work try using this batch file. To run the batch script, save it in a text file and replace the file extension with `.bat` instead of `.txt`
```BAT
@echo off
set RCO_url=https://roblox-client-optimizer.simulhost.com/ClientAppSettings.json
set RobloxVersionDir=C:\Users\%username%\AppData\Local\Roblox\Versions

powershell -Command "(New-Object System.Net.WebClient).DownloadFile('%RCO_url%', 'RCO.json')"

for /f "delims=" %%I in ('dir /b /ad /o-d "%RobloxVersionDir%\version-*"') do (
    set LatestRobloxVersionDir=%RobloxVersionDir%\%%I
    goto :WriteRCO
)

:WriteRCO
if not exist "%LatestRobloxVersionDir%\ClientSettings" (
    mkdir "%LatestRobloxVersionDir%\ClientSettings"
)

copy /y "RCO.json" "%LatestRobloxVersionDir%\ClientSettings\ClientAppSettings.json" >nul

del "RCO.json"

echo New data has been written to %LatestRobloxVersionDir%\ClientSettings\ClientAppSettings.json
```

**Comment by o9zs** [comment]
I just realized what was wrong. I live in Russia and the website is blocked here so it returns this:
![image](https://github.com/ShashTheEpic/RCO-Auto-Installer/assets/99386990/61c125f3-fa65-4561-80c8-c70d8fb4b001)
I replaced the URL with [https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/assets/ClientAppSettings.json](https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/assets/ClientAppSettings.json) and it worked perfectly, thx

**Comment by ShashTheEpic** [comment]
Great to hear that it was resolved! I'll later one update `RCO_Url` to the raw GitHub contents and add the present link as an alternative.
